export default {
  WHITE_COLOR: 'white',
  BLACK_COLOR: 'black',
  LIGHTGRAY_COLOR: '#EAEAEA',
  SEARCH_GRAY_COLOR: '#B4B4B4',
  HEADER_COLOR: '#DEDEDE',
  SHADOW_COLOR: '#F2F5FC',
  BACKGROUND_COLOR: '#F4F4F4',
  BORDER_COLOR: '#CBCBCA',
  DARK_GRAY: '#4E4E4E',
  GREEN_COLOR: '#7AC692'
}